apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourguide-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tourguide
  template:
    metadata:
      labels:
        app: tourguide
    spec:
      containers:
      - name: tourguide
        image: tourguide-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mysql://mysql:3306/TourGuide?useUnicode=true&characterEncoding=UTF-8"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "2003"
---
apiVersion: v1
kind: Service
metadata:
  name: tourguide-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: tourguide
